### ISSUE TITLE
game is a naval warfare bootleg

### ISSUE THREAD

**Issue by checkraisefold** [EletricalFuse/NWR#18]
this feels like a freemodel naval warfare with the "new nwr" game
can we go back to the old code

**Comment by EletricalFuse** [comment]
No, the old code would not work with a mobile audience.

**Comment by EletricalFuse** [comment]
> No, the old code would not work with a mobile audience.

To add to this, the old code is really broken now, it does not work anymore for some reason. If we were to implement that code, not only would it not work at all, it would not be mobile friendly, therefore rendering it as a Dead Ahead 2.0.

**Comment by checkraisefold** [comment]
> > No, the old code would not work with a mobile audience.
> 
> To add to this, the old code is really broken now, it does not work anymore for some reason. If we were to implement that code, not only would it not work at all, it would not be mobile friendly, therefore rendering it as a Dead Ahead 2.0.

so instead of adapting the old code, which is well made and well managed to work for a mobile audience, you instead redesign the whole game and codebase? half of the code you replaced it with is copy+pasted from Plane Wars and is shockingly poorly written. the new game design is very similar to naval warfare and uses garbage touch based regen buttons instead of something normal like proximity prompts. sure you've made the game mobile friendly while simultaneously shitcoding it and completely transforming the game design to something that completely lacks uniqueness

**Comment by checkraisefold** [comment]
sources are telling me the old code worked with mobile so this excuse is just bogus

**Comment by EletricalFuse** [comment]
> Just to reaffirm what I said, the old code does not work anymore, hence all of the issues testers experience when joining the old NWR, such as the game never loading, not being able to spawn in, etc. And the code in the old NWR is so complex, it is extremely difficult to interpret and modify, which is the main reason why we discarded it, it is just not suitable in the long run. The game lacks 'uniqueness' because the game still is missing primordial assets and functions, which explains why it appears so bare-bones. The formatting of the code is not the best since John is not the best programmer. But will eventually rewrite the code with Plain's help (hopefully). The old code DID work with mobile, but would not perform as well as you or I expected. Terrain water requires way more resources to render and display properly than part/mesh water. This can be reinterpreted with Dead Ahead's intense resource usage. Only the best mobile devices would be able to run the old NWR properly. (Which is a minute percentage of the entire mobile population) 

The game will not release until the majority of testers believe the game is truly done.

**Comment by checkraisefold** [comment]
if the game is missing so much then why did jawn say nwr is "99.9%" done

**Comment by checkraisefold** [comment]
nevermind lol
![image](https://user-images.githubusercontent.com/19525688/177422091-56247408-14df-4785-acdf-829f45937286.png)
