### ISSUE TITLE
Cruiser Torpedo Launcher

### ISSUE THREAD

**Issue by LordSuperSucc** [EletricalFuse/NWR#19]
Whenever you fire a volley of torpedoes, a lag spike occurs. 

Firing torpedoes constantly will bug out the gun models and turn them to gray boxes.

Firing a torpedo volley after firing another volley will make the first volley repeat the same firing animation, even after the fact it has already been fired. The animation is the curving downward and back up animation.

Firing torpedoes enough times will make it so less and less torpedoes will be fired. Normal volleys are made up of 5 torpedoes, but fire enough times and soon volleys become 1 or 2 torpedoes at a time.

**Comment by Derpmasternoob** [comment]
Adding on to this, some torpedoes will not go to the surface when you fire like this.
