### ISSUE TITLE
after crashing or dying stuck in lobby cannot rejoin - unless you reset again

### ISSUE THREAD

**Issue by PointyMctest** [EletricalFuse/NWR#44]
after crashing plane at enemy harbour stuck in lobby cannot rejoin - well didnt really crash just that you despawn if you touch the enemy harbour space

**Comment by Derpmasternoob** [comment]
you despawn? i crashed my plane into the harbor and I could still spawn back in

**Comment by PointyMctest** [comment]
you die if you touch the enemy harbour and then i get stuck in lobby can't rejoin the game

**Comment by PointyMctest** [comment]
plus I had islands captured and could only rejoin the harbour
