### ISSUE TITLE
Letter C doesnt color correctly when you claim the island

### ISSUE THREAD

**Issue by PointyMctest** [EletricalFuse/NWR#48]
C stays white circle, while A goes red or blue correctly - see image I had gotten C and then A as japan
![image](https://user-images.githubusercontent.com/99589937/178353823-bde02fd0-ec63-4977-a7d9-fb651c0b0bfe.png)

**Comment by Derpmasternoob** [comment]
Seems it only happens sometimes
<img width="213" alt="image" src="https://user-images.githubusercontent.com/88403853/178361686-c1c6a66a-f8de-483d-90c7-a1c3522bbfb1.png">
I capped all islands with usa

**Comment by PointyMctest** [comment]
yeah with usa it works ok not japan
